### ISSUE TITLE
Can't connect to database (error)

### ISSUE THREAD

**Issue by profyoo** [little-brother/odbc-wlx#4]
I installed the plugin to view Excel (.xlsx) files.
In Quick View (Ctrl+Q), an error message occrued, saying "Can't connect to database".
In Lister (F3), the plugin shows the same error.
Please help me me view Excel files.

① the Excel file 
[카드내역.xlsx](https://github.com/little-brother/odbc-wlx/files/13665321/default.xlsx)

② Office LTSC 2310, 64bit version.

![excel version](https://github.com/little-brother/odbc-wlx/assets/45300802/272c1b27-15ba-43e8-aefb-2a91a9f2381a)

③ Windows 10 
(version 22H2, build 19045.3570)

④ Total Commander 11.02

⑤ error message
![odbc-wlx error message](https://github.com/little-brother/odbc-wlx/assets/45300802/91d02b87-9a91-4ad0-ae8f-a4abbb7f6ec0)

**Comment by little-brother** [comment]
There is nothing wrong with your file. It can be opened in my TC. So I suppose that the issue is related to an ODBC driver. You should validate that you have it. If you use TC x64 then run `odbcad32`; if you use TC x32 then run `%WINDOWS%\SysWOW64\odbcad32`. Then open "User DSN" tab.  Check that you have Excel driver in a list. If there is no Excel driver then you should install [Microsoft Access Database Engine](https://www.microsoft.com/en-us/download/details.aspx?id=54920).

Another place to check: maybe your file has too long path. Copy it to a disk root and try to open.

**Comment by profyoo** [comment]
maybe your file has too long path. Copy it to a disk root and try to open.
→ I checked that, but it is not the cause.

I use TC x32, so I ran C:\Windows\SysWOW64\odbcad32.exe.

It says I don't have the Excel driver, so I installed  Microsoft Access Database Engine.

![before and after Microsoft Access Database Engine](https://github.com/little-brother/odbc-wlx/assets/45300802/c265d00e-678a-4ded-ad58-2f436912fc6b)


However, I still see the Can't connect to database (error).

Anyway, thank you for your help.

You can close this issue. I am OK with it.

**Comment by little-brother** [comment]
Are you install `Microsoft Access Database Engine` 32bit?

> I use TC x32

Definitely it's a not good choice. 32-bit apps are emulated on 64-bit OS with performance loss.

**Comment by profyoo** [comment]
Are you install Microsoft Access Database Engine 32bit?

→ 32bit showed that I use office x64, so Database Engine 32bit cannot be installed.
I downloaded and installed 64bit Engine.

The image I attached above is a before & after image.
After I installed the engine, it says I have 64bit platform.

**Comment by little-brother** [comment]
If you want to use TC x32 and ODBC-plugin then you need 32-bit ODBC drivers => Microsoft Access Database Engine x32.
Perhapse you can force Windows to install it: the installer has command line keys for this. But I can't recommend to do this because it can influent on other applications. The best way is to switch to TC x64.

**Comment by profyoo** [comment]
As you recommended, I ran Total Commander 64bit ( D:\Totalcmd\TOTALCMD64.EXE )

Surprisingly, the xlsx file can be seen with Quick View (Ctrl+Q).
Issue solved!

Thank you.
